### ISSUE TITLE
Refresh token does not automatically renew.

### ISSUE THREAD

**Issue by pibrizo** [Darkness4/withny-dl#41]
![Image](https://github.com/user-attachments/assets/1518fc1d-2b85-41dd-9dbc-226cfb6f70d8)

Hello, I really appreciate this program and use it frequently.
I am a Windows 10 user.
I've recently encountered an issue and I'm not sure what to do.
Do I need to wait for the refresh token to be renewed?
If it doesn't update automatically, could you please advise what steps I should take?
I don't know how to resolve this problem.
I would greatly appreciate any guidance you can provide.

**Comment by Darkness4** [comment]
Hello,

Based on the logs, it's seems the program is unable to load the credentials? (`file does not exist`). Since you are on Windows, you should follow Windows path style (`C:\\path\to\credentials.yaml`, `.\relative\path\to\credentials.yaml`)

Does your configs looks like this:

```yaml
# config.yaml
credentialsFile: 'credentials.yaml'

...
```

```yaml
# credentials.yaml
token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVXVpZCI6IjhhMzliZTY3LTMwOGItNDc3Ni1hOTUxLTdjYzRjOWJlMTA2NSIsInRva2VuVXVpZCI6Ijg4MDA2MmQ2LWY3MmMtNDBlOC04YTliLThhMDUxNjk3ZThmZCIsInNjb3BlIjoidXNlciIsImlhdCI6MTc0MTUyNzQ2MSwiZXhwIjoxNzQxNjEzODYxfQ.<secret>'
refreshToken: <20 chars secret>
```

(please use token authentication as withny has made login by username/password impossible since 12 hours ago)

Usual logs looks like:

```shell
2:41PM INF github.com/Darkness4/withny-dl/cmd/watch/watch_command.go:149 > listening listenAddress=:3000
2:41PM INF github.com/Darkness4/withny-dl/cmd/watch/watch_config.go:73 > initial config detected
2:41PM INF github.com/Darkness4/withny-dl/cmd/watch/watch_config.go:190 > loaded new config
2:41PM INF github.com/Darkness4/withny-dl/cmd/watch/watch_command.go:210 > no notifier configured
dummy notify:
title: config reloaded
message:
2:41PM INF github.com/Darkness4/withny-dl/withny/api/client.go:336 > refreshing token
...
```
