### ISSUE TITLE
Too many 502 error with `/api/streams/with-rooms`

### ISSUE THREAD

**Issue by kice** [Darkness4/withny-dl#47]
```html
withny-dl: watcher of  thrown an error
**watcher of  thrown an error**

HTTP error GET https://www.withny.fun/api/streams/with-rooms, code=502, body=<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

There will one every 10 minutes or so, and I changed config tried to slow down to see if it could improve or not:
```yaml
defaultParams:
  waitPollInterval: '15s'

rateLimitAvoidance:
  pollingPacing: 1500ms
```

**Comment by Darkness4** [comment]
502 errors are caused by server downtime.

**Comment by kice** [comment]
Any chance that allow us to suppress this error notification?

**Comment by Darkness4** [comment]
You could suppress the errors altogether:

```yaml
notifier:
  notificationFormats:
    ## Error happens when something bad happens with the downloading of the stream.
    ## Error like this can be user or developper related.
    ## Available fields:
    ##   - ChannelID
    ##   - Error
    ##   - Labels
    error:
      enabled: false # <- this
      # title: 'watcher of {{ .ChannelID }} thrown an error'
      # message: '{{ .Error }}'
      # priority: 10

    ## LoginFailed happens when the login failed.
    ## Available fields:
    ##   - Error
    loginFailed:
      enabled: true # <- this
      # title: "login failed"
      # message: "{{ .Error }}"
      # priority: 10

```

If you still want errors, but surgically filtered, I'd recommend setting up a log monitoring stack, such as the classic Promtail-GrafanaLoki-Grafana (I use Vector-VictoriaLogs-Grafana myself).
